#!/usr/bin/perl
print "ip: ";
$str = <STDIN>;
$str =~ s/[0-9\n]+//g;
#if( $str =~ /([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})/ ) {
if( ($str cmp "...") == 0) {
	print "올바른 IP주소 형식입니다.\n";
}
else { print "올바르지 않은 IP주소 형식입니다.\n";}
