#!/usr/bin/perl

open(FILE, "score2.txt");
$line0 = <FILE>;
@lines = <FILE>;

close(FILE);

@word = split(/[ \n]+/, $line0);
print "@word  총점  평균\n";
$cnum = @word;
@SUM = (0,0);
$count = 0;

foreach $line (@lines){
	@word = split(/[ \n]+/, $line);
	printf "%-4s %-6s", @word[0], @word[1];
	$sum = 0;
	for($i = 2; @word - $i > 0; $i++) {
		print "  ";
		printf "%-3d", @word[$i];
		$sum += @word[$i];
		@SUM[$i] += @word[$i];
	}
	print "  ";
	$a = @word -2;
	if ($a ==0) { last; }
	$avg = $sum/$a;
	printf "%-4d %-4.1f",$sum, $avg;
	print "\n";

	$count++;
}
for($i = 2; $cnum - $i > 0; $i++) {
            
                printf "%-5.1f", @SUM[$i]/$count;
        }

print "\n";

